# Generated by Django 4.0.5 on 2022-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='additional_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donator',
            name='home_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donator',
            name='ssn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donator',
            name='work_phone',
            field=models.IntegerField(),
        ),
    ]
