# Generated by Django 4.0.5 on 2022-06-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donators', '0002_alter_donator_additional_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donator',
            old_name='birth_Date',
            new_name='birth_date',
        ),
    ]
