# Generated by Django 4.0.5 on 2022-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donators', '0003_rename_birth_date_donator_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='additional_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='donator',
            name='home_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='donator',
            name='work_phone',
            field=models.CharField(max_length=25),
        ),
    ]
