# Generated by Django 4.0.5 on 2022-06-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donators', '0003_rename_birth_date_donator_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=10)),
                ('donation_date', models.DateField()),
                ('donation_amount', models.IntegerField()),
                ('donation_memo', models.CharField(max_length=255)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donators.donator')),
            ],
        ),
    ]
